CREATE TABLE `tasks` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NULL DEFAULT NULL,
	`email` VARCHAR(255) NULL DEFAULT NULL,
	`comment` TEXT NULL DEFAULT NULL,
	`completed` BIT(1) NULL DEFAULT b'0',
	`edit` BIT(1) NULL DEFAULT b'0',
	PRIMARY KEY (`id`)
)
ENGINE=InnoDB
AUTO_INCREMENT=1;

CREATE TABLE `users` (
	`login` VARCHAR(50) NULL DEFAULT NULL,
	`password` VARCHAR(50) NULL DEFAULT NULL,
	`isAdmin` BIT(1) NOT NULL DEFAULT b'0'
)
ENGINE=INNODB;

INSERT INTO `users` VALUES
('admin', '123', 1),
('user', '123', 0)
